name: cd
on:
  push:
    branches: [ci]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          cache: true
          cache-dependency-path: '**/go.sum'
          go-version: '~1.19.4'
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.3.6'
#      - name: Run unit tests
#        run: scripts/unit-tests.sh
      - name: Run e2e tests
        run: scripts/e2e-tests.sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          CGO_ENABLED: '0'
#      - name: Deploy to prod
#        run: scripts/deploy.sh prod
#        env:
#          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#          TF_VAR_EMAIL: ${{ secrets.EMAIL }}
