name: cd
on:
  push:
    branches: [main]
jobs:
  validate:
    uses: ./.github/workflows/validate.yml
    secrets: inherit
  deploy-to-prod:
    needs: validate
    uses: ./.github/workflows/deploy.yml
    with:
      stack: prod
    secrets: inherit
