name: deploy
on:
  workflow_call:
    inputs:
      stack:
        required: true
        type: string
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.3.6'
          terraform_wrapper: false
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            go:
              - 'cmd/**'
      - uses: actions/setup-go@v3
        if: steps.filter.outputs.go == 'true'
        with:
          cache: true
          go-version: '~1.19.4'
      - name: Install dependencies
        if: steps.filter.outputs.go == 'true'
        run: go get ./...
      - name: Build and push to S3
        if: steps.filter.outputs.go == 'true'
        run: scripts/build.sh ${{ inputs.stack }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-west-1
      - name: Deploy ${{ inputs.stack }} stack
        run: scripts/deploy.sh ${{ inputs.stack }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_VAR_email: ${{ secrets.EMAIL }}
