name: validate
on:
  workflow_call:
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          cache: true
          go-version: '~1.19.4'
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.3.6'
          terraform_wrapper: false
      - name: Install dependencies
        run: go get -t ./...
      - name: Run unit tests
        run: go test -v ./cmd/...
      - name: Run e2e tests
        run: go test -v ./tests
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
